window._env_ = {
  CLIENTID: "test-subscription",
  CURRENCY: "INR",
  KEYCLOAK_URL: "https://auth.dailykit.org/auth",
  KEYCLOAK_CLIENT="dashboard-dev",
  KEYCLOAK_REALM = "accounts",
  DATA_HUB_WSS: "wss://test.dailykit.org/datahub/v1/graphql",
  DATA_HUB_HTTPS: "https://test.dailykit.org/datahub/v1/graphql",
  GOOGLE_API_KEY: "AIzaSyDvcHhIx-tLq8127egipZ1WRIbsDE0MN4Q",
  STRIPE_KEY: "pk_live_51FM9jLGKMRh0bTaiJUrOPTdCqSGYZHHuQjrD9a3BlZiA0OgCu4ZwLLTdHGyZ0IU6wYnmWpARvn8KIJCw5UJJcRx300XnnUvFfW",
  DAILYKEY_URL: "https://platform.dailykit.org/payments",
  ADMIN_SECRET: "123456",
  ADMIN_SECRET1: "61fc40e1-e13a-4a63-80bb-4796292f0d9f",
  EXPRESS_URL: "https://test.dailykit.org",
  PLATFORM_URL: "https://platform.dailykit.org",
  DAILYCLOAK_URL: "https://dailycloak.dailykit.org/v1/graphql",
  DAILYCLOAK_SUBS_URL: "wss://dailycloak.dailykit.org/v1/graphql",
  CA_ID: "ca_GzdkmVO7aRw9VA0DlP3hMXkfBWS4ib1r",
  GIPHY_KEY: "rZZfC1XlW0KhwLUGFR3gFkWOSu8RnPrs",
}
